### ISSUE TITLE
Slice out of range error

### ISSUE THREAD

**Issue by capnspacehook** [goretk/gore#10]
Go version I was using: Go 1.13 linux/amd64

I was testing out gore today, and came across a curious bug. I compiled the code below, with no special flags: `go build -trimpath -o test.bin main.go`
I then ran the file against itself `./test.bin test.bin`, and this error occured: 
```
panic: runtime error: slice bounds out of range [:5203186120246329699] with capacity 1001107

goroutine 1 [running]:
github.com/goretk/gore.parseString(0xc0000c6540, 0xfffff8250c8b4864, 0x401000, 0xc000936000, 0xf4693, 0xf4693, 0x0, 0x0)
        github.com/goretk/gore/type.go:785 +0x24e
github.com/goretk/gore.parseUncommonType(0xc0003004b0, 0xc00022f290, 0xc0000c6540, 0xc000936000, 0xf4693, 0xf4693, 0x401000, 0xc00022f140)
        github.com/goretk/gore/type.go:805 +0x40a
github.com/goretk/gore.typeParse(0xc00022f140, 0xc0000c6540, 0xed0, 0xc000936000, 0xf4693, 0xf4693, 0x401000, 0x0)
        github.com/goretk/gore/type.go:387 +0x353f
github.com/goretk/gore.getLegacyTypes(0xc0000c6540, 0x56cec0, 0xc00000e040, 0xa, 0xffffffffffffffff, 0x8)
        github.com/goretk/gore/type.go:107 +0x235
github.com/goretk/gore.getTypes(0xc0000c6540, 0x56cec0, 0xc00000e040, 0x0, 0x4e9c20, 0xc0000b0140)
        github.com/goretk/gore/type.go:47 +0x4cc
github.com/goretk/gore.(*GoFile).GetTypes(0xc0000b0140, 0x0, 0x0, 0x0, 0x0, 0x7762a6bf)
        github.com/goretk/gore/file.go:262 +0x52
main.main()
        command-line-arguments/main.go:21 +0xdc
```
I also came across this error running this code against various other Go ELF files on my system, so it isn't unique to this file.

Code mentioned above: 
```
package main

import (
	"fmt"
	"os"
	"path"

	"github.com/goretk/gore"
)

func main() {
	file, err := gore.Open(os.Args[1])
	if err != nil {
		panic(err)
	}

	packages, err := file.GetPackages()
	if err != nil {
		panic(err)
	}
	types, err := file.GetTypes()
	if err != nil {
		panic(err)
	}

	symbols := make([]string, (len(packages) + len(types)*2))
	for _, goType := range types {
		symbols = append(symbols, path.Join(goType.PackagePath, goType.Name))
	}
	for _, pkg := range packages {
		for _, method := range pkg.Methods {
			symbols = append(symbols, path.Join(method.PackageName, method.Name))
		}
		for _, function := range pkg.Functions {
			symbols = append(symbols, path.Join(function.PackageName, function.Name))
		}
	}

	for _, symbol := range symbols {
		fmt.Println(symbol)
	}
}
```

EDIT: ran compiled binary through `redress` just to make sure I was using gore correctly, and as I thought it panic'd with the same error.

**Comment by TcM1911** [comment]
@capnspacehook, this is a known issue. This caused when incorrect compiler version is detected for the binary. 
```
github.com/goretk/gore.getLegacyTypes(0xc0000c6540, 0x56cec0, 0xc00000e040, 0xa, 0xffffffffffffffff, 0x8)
        github.com/goretk/gore/type.go:107 +0x235
```
is logic for parsing versions prior to 1.7. Since the data structures in these versions are very different this can happen.

When analysing the library with the library this usually happens because the markers for different versions are included in the library.... If you know the version, you can force the assumed version by for example calling `file.SetGoVersion("go1.13")` after opening the file.

Until a better way for determining the version, this is the current solution.

With the release 1.13, a functionality for extracting the version was added but it only works for 1.13 and later stripped binaries:
```
[gore]$ file testdata/gold/gold-linux-amd64-1.13
testdata/gold/gold-linux-amd64-1.13: ELF 64-bit LSB executable, x86-64, version 1 (SYSV), statically linked, Go BuildID=YWmIDeHrc37MnKyHo53S/hGdyCvxmA0ZSwHA56vwG/cthDW6MiJGhvIw_Mk5x0/egx2QKll4Xf19HLolX0e, stripped
[gore]$ go version testdata/gold/gold-linux-amd64-1.13
testdata/gold/gold-linux-amd64-1.13: go1.13
[gore]$ file testdata/gold/gold-linux-amd64-1.12.0
testdata/gold/gold-linux-amd64-1.12.0: ELF 64-bit LSB executable, x86-64, version 1 (SYSV), statically linked, Go BuildID=W11rzA8dxCieF64mk9rO/wmqBULPx6tMOdPbSBabM/X40xrZ4nVRHkrWOKbwZw/JpQDPeWBsrG9Rn_jzf3s, stripped
[gore]$ go version testdata/gold/gold-linux-amd64-1.12.0
testdata/gold/gold-linux-amd64-1.12.0: go version not found
```

**Comment by capnspacehook** [comment]
Ok that makes sense, thanks. I will try explicitly setting the Go version. I know some other binaries I tested threw a different error, I think related to the fact that the buildID wasn't compiled in the with the flag `-ldflags "buildid=" `. I will do some more testing and update the issue.

**Comment by TcM1911** [comment]
Nice find. I raised #11. I'll see if I can get it fixed ASAP.

**Comment by capnspacehook** [comment]
Thanks for the quick fix! Tested the upgraded redress and the issue is fixed!
