### ISSUE TITLE
panic: runtime error: index out of range [757869355] with length 33282560

### ISSUE THREAD

**Issue by nj00001** [goretk/gore#29]
I used redress to analyze a program of about 70mb. When using -struct or -interface, the program reported an error.

github.com/goretk/gore.resolveName(...)
        github.com/goretk/gore@v0.8.14/type.go:980
github.com/goretk/gore.typeParse(0xc000ea1170, 0xc000192e40, 0xed923c, 0xc007bba000, 0x1fbda00, 0x1fbda00, 0x20a5000, 0x0)
        github.com/goretk/gore@v0.8.14/type.go:371 +0x39fb
github.com/goretk/gore.typeParse(0xc000ea1170, 0xc000192e40, 0x284d20, 0xc007bba000, 0x1fbda00, 0x1fbda00, 0x20a5000, 0x0)
        github.com/goretk/gore@v0.8.14/type.go:654 +0x148e
github.com/goretk/gore.typeParse(0xc000ea1170, 0xc000192e40, 0x1dcac0, 0xc007bba000, 0x1fbda00, 0x1fbda00, 0x20a5000, 0x0)
        github.com/goretk/gore@v0.8.14/type.go:418 +0x2529
github.com/goretk/gore.getTypes(0xc000192e40, 0xa05368, 0xc0001120f0, 0x0, 0x9784e0, 0xc00011e280)
        github.com/goretk/gore@v0.8.14/type.go:76 +0x2a5
github.com/goretk/gore.(*GoFile).GetTypes(0xc00011e280, 0x0, 0x0, 0x0, 0x0, 0x0)
        github.com/goretk/gore@v0.8.14/file.go:262 +0x59
main.standalone()
        github.com/goretk/redress/standalone.go:59 +0x308
main.main()
        github.com/goretk/redress/main.go:73 +0x54

**Comment by TcM1911** [comment]
I'm currently working on rewriting the type parsing logic because it's buggy (#25). Hopefully it will address this issue.

**Comment by TcM1911** [comment]
@nj00001, the new parser has been merged into the main development branch for next minor release of the library. I've released a pre-releas of the library that [redress v0.8.0alpha1](https://github.com/goretk/redress/releases/tag/v0.8.0-alpha1) uses. This release includes the new type parser. See if the new parser fixes the issue.
