### ISSUE TITLE
Linux type kind parsing fails

### ISSUE THREAD

**Issue by stevemk14ebr** [goretk/gore#6]
When running the following script on a installation of pygore on a debian system i sometimes see erroneous values for kind. These are parsed correctly on a windows installation, using the same binary. I've verified the binaries are not corrupted by checking their hashes.

```
import pygore
import sys

testfile = sys.argv[1]

f = pygore.GoFile(testfile)
c = f.get_compiler_version()

types = f.get_types()
f.close()
for t in types:
    val,  = t.kind
    if val > 30 :
        print(val)
```

Output:

> 140033113718791
> 140033113718785
> 140033113718803
> 140033113718803
> 140033113718786
> 140033113718809
> 140033113718807

**Comment by TcM1911** [comment]
Can you share the file?

**Comment by stevemk14ebr** [comment]
No i cannot unfortunately, i will try to do some reproduction myself to give you more info. This bug seems weird though because i see you are already masking the kind field?

**Comment by TcM1911** [comment]
Does the Go library parse it correctly? You can either use it directly or use `redress` "https://github.com/goretk/redress/releases" to extract the information. `redress -type` should print out all types in a format you will find in the source code.

When using the python library, the data is transferred from Go to C to Python. The issue can be anywhere in this chain... I suspect the C layer...

**Comment by stevemk14ebr** [comment]
i'm trying with the C bindings now. I'll do the same logic as the python script

**Comment by stevemk14ebr** [comment]
the C library does not exhibit this issue with the following code:
```
include <stdio.h>
#include "libgore.h"

int main(int argc, char** argv)
{
   int v;
   char* fp = argv[1];
   printf("loading: %s", fp);
   v = gore_open(fp);
   struct compilerVersion* c = gore_getCompilerVersion(fp);
   printf("Compiler version: %s\n", c->name);
   struct types* ts = gore_getTypes(fp);
   printf("found %d types\n", ts->length);
   for(int i =0; i < ts->length; i++) {
       struct type* t = ts->types[i];
       if(t->kind > 30) {
           printf("got a bad one\n");
       }
   }
   gore_close(fp);
   return 0;
}
```
This suggest the python bindings have an issue.

**Comment by mattkeenan** [comment]
This is just a complete guess here, but could this be a bignum and/or rounding problem?

x.ref https://github.com/numpy/numpy/issues/8433

**Comment by stevemk14ebr** [comment]
i've seen stuff like this before when the field being assigned into is wider than the value being assigned and is not zeroed before. 

EDIT: I looked, this is the bug. In the python wrapper library an unsigned long is used, but in the c library it's an unsigned int

`_Type._fields_ = [('kind', c_ulong),

struct type {
    unsigned int kind;
`

**Comment by mattkeenan** [comment]
From memory this is because Windows malloc() initialises memory to zero, whereas Linux malloc() doesn't.

**Comment by stevemk14ebr** [comment]
Ah cool thanks for sharing that! Also appreciate the library alot.

**Comment by TcM1911** [comment]
I just pushed a new patch update to pypi https://pypi.org/project/pygore. Please let me know if 0.2.3 does not solve the issue.

**Comment by stevemk14ebr** [comment]
Tested. The bug is resolved.
