### ISSUE TITLE
Replacing extracted information

### ISSUE THREAD

**Issue by CaledoniaProject** [goretk/gore#68]
How can I overwrite/replace the extracted information in the compiled binary? e.g BuildID, package names etc. I didn't see any exposed methods that can do this.

**Comment by CaledoniaProject** [comment]
A better plan, can you modify the golang types structure and add an offset variable?

**Comment by TcM1911** [comment]
It's not designed to do any binary patching.

**Comment by CaledoniaProject** [comment]
@TcM1911 I just need your library to expose the offsets, I will do the modification myself.
