### ISSUE TITLE
codecov/codecov-action v1 will not work after 2024 Feb 1

### ISSUE THREAD

**Issue by Zxilly** [goretk/gore#80]
As https://github.com/codecov/codecov-action said:
> Deprecation of v1
> As of February 1, 2022, v1 has been fully sunset and no longer functions

>
> Due to the [deprecation](https://about.codecov.io/blog/introducing-codecovs-new-uploader/) of the underlying bash uploader, the Codecov GitHub Action has released v2/v3 which will use the new [uploader](https://github.com/codecov/uploader). You can learn more about our deprecation plan and the new uploader on our [blog](https://about.codecov.io/blog/introducing-codecovs-new-uploader/).

>
> We will be restricting any updates to the v1 Action to security updates and hotfixes.

But update to v2/v3 required a token from codecov, which can only be set by maintainer. It's hard to create to pr to fix this.

**Comment by TcM1911** [comment]
Fixed in #82. Token wasn't needed for public repos: https://github.com/marketplace/actions/codecov
